server:
  port: 8080
#
## 对象
#student:
#  name: huhaisen
#  age: 21
#
#  # 行内写法
#student: {name: huhais, age: 21}

#### yaml可以直接给

##########  指定模板所在目录 css js 才能生效, 但是现在注释掉了好像也可以呀 ？？？？？？？？？ #####################
#thymeleaf:
#  prefix: classpath:/templates/  #prefix：指定模板所在的目录
#  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
#  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
#  suffix:  .html
#  #encoding: UTF-8
#  #content-type: text/html
#  mode: HTML5

person:
  name: huhaisen${random.uuid}
  age: ${random.int}
  happy: true
  birth: 2002/04/09
  maps: {k1: v1, k2: v2}
  lists:
    - code
    - music
    - girls
  dog:
    name: ${person.hello:hello}_旺财
    age: 3

dog:
  first-name: 黑虎
  age: 12



spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/visualization_class?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.studyself.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
